### ISSUE TITLE
Nice lib - not yet usable

### ISSUE THREAD

**Issue by AmirTugi** [RelaxedJS/ReLaXed#104]
The lib is indeed nice and modern, but unfortunately I cannot use it yet because of how complex it makes my NodeJS RESTAPI server when making a pdf doc:
I can't generate the PDF into a var (inline in my server, and not as external process)

All the other reasons are actually a consequence of the above. as it makes the process too complex.

**Comment by Zulko** [comment]
That's because it's not a lib. As said in the first line of the README, ReLaXed is meant for interactive use, it is primarily a desktop command-line app. Some people use it on REST API, and there is some push for a more server-friendly version, but I am not sure what advantages this would have compared to making your own puppeteer-based API in literally 10 lines of code (see [this comment](https://github.com/RelaxedJS/ReLaXed/issues/98) on basically the same issue as yours).
