### ISSUE TITLE
global install

### ISSUE THREAD

**Issue by DanielRuf** [RelaxedJS/ReLaXed#11]
It should work. At least I do not have any issues using puppeteer for my `website-stack` package and using it globally.

**Comment by Zulko** [comment]
I saw your pull request for a docs change, but I prefer to wait until several people can confirm that they successfully installed ReLaXed globally. Then it would still be worth it to suggest the global method along with the local install, or else some people might have difficulties (global install didnt work for me on linux because of the permission settings on the folder in which npm installs its global libraries).

**Comment by Adrion** [comment]
## Environment 
 - OSX 13.4
 - node 9.2.0
 - npm 6.0.0

## Method
`$ npm i relaxedjs -g` (without sudo) 

No problem, and works as expected 👍

**Comment by Zulko** [comment]
Thank you very much. Maybe I messed up my Node setup at some point (problems with authorization etc.).

I will update the README, and move my local installation instructions to troubleshooting.

**Comment by DanielRuf** [comment]
@Zulko you mean https://github.com/RelaxedJS/ReLaXed/pull/16?

**Comment by Zulko** [comment]
Yes but with a link to the wiki's troubleshooting section

**Comment by DanielRuf** [comment]
Sounds good =)

**Comment by Zulko** [comment]
Done ! Anyone meeting problems with the global install, please open a new issue
