### ISSUE TITLE
Is relaxed.js is completely asynchronous ?

### ISSUE THREAD

**Issue by awesomehimanshu** [RelaxedJS/ReLaXed#62]
When i see examples you provided https://github.com/RelaxedJS/ReLaXed-examples
all are pug . why not you have given any example for html to pdf ?

Is there is any limitation?

why it always give me mobile view pdf when i use html ? is there are any label to provide to make the pdf as desktop view.

According to your docs the relexed.js check for html or pug will changes , if the file changes it generate pdf with respect to it .

Why not we are using relexed.js for creating pdf when i want?

Is there is any example of it where it not check regularly ? and create pdf when we want ?

**Comment by Zulko** [comment]
ReLaXed should work perfectly with HTML. The examples show Pug because I want to encourage Pug usage. Not sure about the "mobile view" for HTML, sounds like a bug, can you give more details just so I can see if i observe the same ?

Since a few days ago you can add the ``--build-once`` option to just build the PDF instead of watching. This is documented in the wiki but given how many people ask for it I will add some explanations in the main README.

https://github.com/RelaxedJS/ReLaXed/wiki/Features#starting-relaxed

**Comment by Zulko** [comment]
Done for the readme. Im closing this. Can you open a specific issue for the "mobile view" bug ?
