### ISSUE TITLE
Running `relaxed` without any arguments prints `undefined` to stdout

### ISSUE THREAD

**Issue by Calinou** [RelaxedJS/ReLaXed#82]
**OS:** Fedora 27
**Node.js version:** 8.11.2

Running `relaxed` in a terminal without any arguments provided will provide unhelpful output:

```
❯ relaxed
undefined
```

An help text should probably be displayed instead, as is done by `relaxed -h`.

**Comment by Zulko** [comment]
I agree that "undefined" is a very bad feedback. The intention in the future is to have ReLaXed auto-discover an input file when none is provided:

- if there is only one pug document in the current folder, choose that one.
- If there are several, but one is called master.pug, choose that one
- If there is no pug document in the current folder, say that none were found and display a help text

This would allow you to just type ``relaxed`` in your current directory to get started,
```
relaxed my_project_dir/
```
instead of 

```
relaxed my_project_dir/master.pug
```

**Comment by Calinou** [comment]
This sounds good to me.

> If there are several, but one is called master.pug, choose that one

Why not `index.pug` instead? It would be consistent with the standard `index.html` naming that is used on Web servers.

**Comment by Zulko** [comment]
Even though ReLaXed uses web techs and the first users will certainly come from front-end, I will try to make it as friendly as possible to people who are not from the field, which implies avoiding any standards which would be familiar to web developers but confusing to newcomers.

"Master" document is a common name in publishing for the document that gets ultimately rendered, but I could also support "index.pug" or even "main.pug" as possible default input names, so that everyone is happy.

**Comment by Zulko** [comment]
The last commit introduces "master-file auto-detection" (and displays help if no input is provided and no master-file is detected).
